# Generated by Django 2.0.2 on 2018-02-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("modeemintternet", "0016_auto_20180207_2250")]

    operations = []
