# Generated by Django 2.0.2 on 2018-02-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeemintternet', '0016_auto_20180207_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('format', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'format',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShadowFormat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('format', models.CharField(max_length=32)),
                ('hash', models.CharField(max_length=1024)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'shadowformat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroupMember',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'usergroupmember',
                'managed': False,
            },
        ),
    ]
