# Generated by Django 2.0.2 on 2018-02-07 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeemintternet', '0017_format_shadowformat_usergroupmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='bank_reference',
        ),
    ]
