# Generated by Django 2.0.2 on 2018-02-07 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("modeemintternet", "0020_auto_20180207_2341")]

    operations = [
        migrations.RemoveField(model_name="event", name="poster"),
        migrations.DeleteModel(name="Event"),
    ]
