# Generated by Django 2.0.2 on 2018-02-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("modeemintternet", "0022_auto_20180211_1501")]

    operations = [
        migrations.RemoveField(model_name="application", name="pbkdf2_sha256")
    ]
