# Generated by Django 2.0.2 on 2018-02-12 18:46

from django.db import migrations, models
import modeemintternet.models


class Migration(migrations.Migration):

    dependencies = [
        ('modeemintternet', '0023_remove_application_pbkdf2_sha256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='username',
            field=models.CharField(max_length=32, validators=[modeemintternet.models.validate_username]),
        ),
    ]
