# Generated by Django 2.2.4 on 2019-08-07 12:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("modeemintternet", "0024_auto_20180212_2046"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipFee",
            fields=[
                (
                    "year",
                    models.PositiveIntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1975),
                            django.core.validators.MaxValueValidator(2020),
                        ],
                        verbose_name="Vuosi",
                    ),
                )
            ],
            options={
                "verbose_name": "Jäsenmaksu",
                "verbose_name_plural": "Jäsenmaksut",
                "ordering": ["year"],
                "get_latest_by": ["year"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lifetime",
                    models.BooleanField(default=False, verbose_name="Ainaisjäsenyys"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="Kotikunta"
                    ),
                ),
                (
                    "key_engineering",
                    models.BooleanField(
                        default=False, verbose_name="Konehuoneen kova-avain"
                    ),
                ),
                (
                    "key_physical",
                    models.BooleanField(
                        default=False, verbose_name="Kerhohuoneen kova-avain"
                    ),
                ),
                (
                    "key_virtual",
                    models.BooleanField(
                        default=False, verbose_name="Kerhohuoneen virtuaaliavain"
                    ),
                ),
                (
                    "fee",
                    models.ManyToManyField(
                        to="modeemintternet.MembershipFee", verbose_name="Jäsenmaksut"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Käyttäjä",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jäsenyys",
                "verbose_name_plural": "Jäsenyydet",
                "ordering": ["user__username"],
            },
        ),
    ]
