# Generated by Django 2.2.4 on 2019-08-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeemintternet', '0025_membership_membershipfee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipfee',
            options={'get_latest_by': ['year'], 'ordering': ['-year'], 'verbose_name': 'Jäsenmaksu', 'verbose_name_plural': 'Jäsenmaksut'},
        ),
    ]
