# Generated by Django 2.2.4 on 2019-08-27 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("modeemintternet", "0033_auto_20190828_0015")]

    operations = [
        migrations.AlterField(
            model_name="shadow",
            name="username",
            field=models.OneToOneField(
                db_column="username",
                db_constraint=False,
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                primary_key=True,
                serialize=False,
                to="modeemintternet.Passwd",
            ),
        ),
        migrations.AlterField(
            model_name="shadowformat",
            name="format",
            field=models.ForeignKey(
                db_column="format",
                db_constraint=False,
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="modeemintternet.Format",
            ),
        ),
        migrations.AlterField(
            model_name="shadowformat",
            name="username",
            field=models.ForeignKey(
                db_column="username",
                db_constraint=False,
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="modeemintternet.Passwd",
            ),
        ),
        migrations.AlterField(
            model_name="usergroupmember",
            name="groupname",
            field=models.ForeignKey(
                db_column="groupname",
                db_constraint=False,
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="modeemintternet.UserGroup",
            ),
        ),
        migrations.AlterField(
            model_name="usergroupmember",
            name="username",
            field=models.ForeignKey(
                db_column="username",
                db_constraint=False,
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="modeemintternet.Passwd",
            ),
        ),
    ]
