# Generated by Django 2.2.8 on 2019-12-12 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("modeemintternet", "0034_auto_20190828_0103"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="poster",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
