# Generated by Django 3.1.7 on 2021-02-22 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeemintternet", "0035_auto_20191212_1852"),
    ]

    operations = [
        migrations.RemoveField(model_name="application", name="des_crypt",),
        migrations.RemoveField(model_name="application", name="md5_crypt",),
    ]
