# Generated by Django 4.1.4 on 2024-02-01 00:52

import django.core.validators
from django.db import migrations, models
import modeemintternet.models


class Migration(migrations.Migration):

    dependencies = [
        ("modeemintternet", "0038_application_md5_crypt"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="validation",
            field=models.CharField(
                default="",
                max_length=16,
                validators=[modeemintternet.models.validate_antibot_question],
            ),
        ),
        migrations.AlterField(
            model_name="membershipfee",
            name="year",
            field=models.PositiveIntegerField(
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(1975),
                    django.core.validators.MaxValueValidator(2025),
                ],
                verbose_name="Vuosi",
            ),
        ),
    ]
