# Generated by Django 5.1.15 on 2025-12-05 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeemintternet", "0039_feedback_validation_alter_membershipfee_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipfee",
            name="year",
            field=models.PositiveIntegerField(
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(1975),
                    django.core.validators.MaxValueValidator(2026),
                ],
                verbose_name="Vuosi",
            ),
        ),
    ]
