#!/bin/bash

# https://github.com/docker/hub-feedback/issues/600#issuecomment-613335933

set -euxo pipefail

echo "SOURCE_COMMIT: $SOURCE_COMMIT"

if [[ -z "$SOURCE_COMMIT" ]]; then
	export SOURCE_COMMIT="${SOURCE_COMMIT:-$(git rev-parse --short HEAD)}"
	echo "Updating SOURCE_COMMIT from git rev-parse --short HEAD"
	echo "SOURCE_COMMIT: $SOURCE_COMMIT"
fi

echo "DOCKER_TAG: $DOCKER_TAG"

docker build -t "${IMAGE_NAME}" --build-arg "SOURCE_COMMIT=${SOURCE_COMMIT}" --build-arg "DOCKER_TAG=${DOCKER_TAG}" .
