name: Build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    # https://docs.github.com/en/free-pro-team@latest/actions/guides/creating-postgresql-service-containers
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: modeemintternet
          POSTGRES_PASSWORD: modeemintternet
          POSTGRES_DB: modeemiuserdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox tox-gh-actions

    - name: Run tox quality gates
      run: |
        tox -v

    - name: Upload coverage
      uses: codecov/codecov-action@v1
